//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONELLER
    {
        public int personel_id { get; set; }
        public string personel_ad { get; set; }
        public string personel_soyad { get; set; }
        public string personel_TC { get; set; }
        public string personel_tel { get; set; }
        public string personel_mail { get; set; }
        public string personel_kullanıciad { get; set; }
        public string personel_sifre { get; set; }
        public string personel_foto { get; set; }
        public string personel_adres { get; set; }
    }
}
