//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UYELER()
        {
            this.TBL_ODUNC = new HashSet<TBL_ODUNC>();
        }
    
        public int uye_id { get; set; }
        public string uye_ad { get; set; }
        public string uye_soyad { get; set; }
        public string uye_TC { get; set; }
        public string uye_tel { get; set; }
        public string uye_mail { get; set; }
        public string uye_adres { get; set; }
        public Nullable<double> uye_ceza { get; set; }
        public string uye_cinsiyet { get; set; }
        public string uye_dTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODUNC> TBL_ODUNC { get; set; }
    }
}
