//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KAYNAKLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_KAYNAKLAR()
        {
            this.TBL_ODUNC = new HashSet<TBL_ODUNC>();
        }
    
        public int kaynak_id { get; set; }
        public string kaynak_isbn { get; set; }
        public string kaynak_ad { get; set; }
        public string kaynak_yazar { get; set; }
        public string kaynak_yayinevi { get; set; }
        public Nullable<int> kaynak_basımtarihi { get; set; }
        public Nullable<int> kaynak_sayfa { get; set; }
        public string kaynak_tur { get; set; }
        public string kaynak_ulke { get; set; }
        public string kaynak_dil { get; set; }
        public Nullable<int> kaynak_adet { get; set; }
        public string kaynak_raf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ODUNC> TBL_ODUNC { get; set; }
    }
}
