//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ODUNC
    {
        public int odunc_id { get; set; }
        public Nullable<int> kitap_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<System.DateTime> alis_tarih { get; set; }
        public Nullable<System.DateTime> veris_tarih { get; set; }
        public Nullable<bool> durm { get; set; }
    
        public virtual TBL_KAYNAKLAR TBL_KAYNAKLAR { get; set; }
        public virtual TBL_UYELER TBL_UYELER { get; set; }
    }
}
